# Generated by Django 2.2.6 on 2019-11-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incometraffic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomingmessage", name="delivered_time", field=models.DateTimeField(default=None, null=True),
        ),
    ]
