PROCESSING_MESSAGE_STATUS = "processing"
DELIVERED_MESSAGE_STATUS = "delivered"
FAILED_MESSAGE_STATUS = "failed"

ALIVE_ENDPOINT_STATUS = "live"

DOWN_ENDPOINT_STATUS = "down"

ENDPOINT_STATUSES = [
    (ALIVE_ENDPOINT_STATUS, "live"),
    (DOWN_ENDPOINT_STATUS, "down"),
]

MESSAGE_STATUSES = [
    (PROCESSING_MESSAGE_STATUS, "processing"),
    (DELIVERED_MESSAGE_STATUS, "delivered"),
]

DEFAULT_CURRENCY = "UAH"

SUCCESS_API_MESSAGE_STATUS = "success"
